package ru.geekbrains.android3_7;

public class JsonExample {
    public static final String jsonRepos = "[\n" +
            "  {\n" +
            "    \"id\": 42662933,\n" +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnk0MjY2MjkzMw==\",\n" +
            "    \"name\": \"C45algorithm\",\n" +
            "    \"full_name\": \"marvas/C45algorithm\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"marvas\",\n" +
            "      \"id\": 5663505,\n" +
            "      \"node_id\": \"MDQ6VXNlcjU2NjM1MDU=\",\n" +
            "      \"avatar_url\": \"https://avatars0.githubusercontent.com/u/5663505?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/marvas\",\n" +
            "      \"html_url\": \"https://github.com/marvas\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/marvas/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/marvas/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/marvas/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/marvas/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/marvas/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/marvas/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/marvas/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/marvas/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/marvas/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/marvas/C45algorithm\",\n" +
            "    \"description\": \"Implementation of C4.5 algorithm in python.\",\n" +
            "    \"fork\": true,\n" +
            "    \"url\": \"https://api.github.com/repos/marvas/C45algorithm\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/marvas/C45algorithm/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/marvas/C45algorithm/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/marvas/C45algorithm/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/marvas/C45algorithm/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/marvas/C45algorithm/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/marvas/C45algorithm/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/marvas/C45algorithm/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/marvas/C45algorithm/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/marvas/C45algorithm/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/marvas/C45algorithm/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/marvas/C45algorithm/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/marvas/C45algorithm/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/marvas/C45algorithm/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/marvas/C45algorithm/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/marvas/C45algorithm/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/marvas/C45algorithm/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/marvas/C45algorithm/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/marvas/C45algorithm/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/marvas/C45algorithm/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/marvas/C45algorithm/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/marvas/C45algorithm/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/marvas/C45algorithm/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/marvas/C45algorithm/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/marvas/C45algorithm/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/marvas/C45algorithm/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/marvas/C45algorithm/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/marvas/C45algorithm/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/marvas/C45algorithm/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/marvas/C45algorithm/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/marvas/C45algorithm/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/marvas/C45algorithm/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/marvas/C45algorithm/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/marvas/C45algorithm/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/marvas/C45algorithm/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/marvas/C45algorithm/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/marvas/C45algorithm/deployments\",\n" +
            "    \"created_at\": \"2015-09-17T15:02:39Z\",\n" +
            "    \"updated_at\": \"2015-09-17T15:02:40Z\",\n" +
            "    \"pushed_at\": \"2015-08-26T04:50:49Z\",\n" +
            "    \"git_url\": \"git://github.com/marvas/C45algorithm.git\",\n" +
            "    \"ssh_url\": \"git@github.com:marvas/C45algorithm.git\",\n" +
            "    \"clone_url\": \"https://github.com/marvas/C45algorithm.git\",\n" +
            "    \"svn_url\": \"https://github.com/marvas/C45algorithm\",\n" +
            "    \"homepage\": \"\",\n" +
            "    \"size\": 104,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": \"Python\",\n" +
            "    \"has_issues\": false,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": {\n" +
            "      \"key\": \"mit\",\n" +
            "      \"name\": \"MIT License\",\n" +
            "      \"spdx_id\": \"MIT\",\n" +
            "      \"url\": \"https://api.github.com/licenses/mit\",\n" +
            "      \"node_id\": \"MDc6TGljZW5zZTEz\"\n" +
            "    },\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  },\n" +
            "  {\n" +
            "    \"id\": 13496827,\n" +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxMzQ5NjgyNw==\",\n" +
            "    \"name\": \"DAT210\",\n" +
            "    \"full_name\": \"marvas/DAT210\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"marvas\",\n" +
            "      \"id\": 5663505,\n" +
            "      \"node_id\": \"MDQ6VXNlcjU2NjM1MDU=\",\n" +
            "      \"avatar_url\": \"https://avatars0.githubusercontent.com/u/5663505?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/marvas\",\n" +
            "      \"html_url\": \"https://github.com/marvas\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/marvas/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/marvas/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/marvas/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/marvas/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/marvas/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/marvas/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/marvas/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/marvas/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/marvas/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/marvas/DAT210\",\n" +
            "    \"description\": \"Project PictureViewer\",\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/marvas/DAT210\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/marvas/DAT210/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/marvas/DAT210/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/marvas/DAT210/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/marvas/DAT210/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/marvas/DAT210/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/marvas/DAT210/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/marvas/DAT210/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/marvas/DAT210/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/marvas/DAT210/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/marvas/DAT210/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/marvas/DAT210/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/marvas/DAT210/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/marvas/DAT210/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/marvas/DAT210/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/marvas/DAT210/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/marvas/DAT210/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/marvas/DAT210/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/marvas/DAT210/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/marvas/DAT210/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/marvas/DAT210/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/marvas/DAT210/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/marvas/DAT210/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/marvas/DAT210/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/marvas/DAT210/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/marvas/DAT210/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/marvas/DAT210/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/marvas/DAT210/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/marvas/DAT210/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/marvas/DAT210/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/marvas/DAT210/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/marvas/DAT210/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/marvas/DAT210/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/marvas/DAT210/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/marvas/DAT210/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/marvas/DAT210/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/marvas/DAT210/deployments\",\n" +
            "    \"created_at\": \"2013-10-11T11:00:34Z\",\n" +
            "    \"updated_at\": \"2013-10-11T11:19:00Z\",\n" +
            "    \"pushed_at\": \"2013-10-11T11:18:58Z\",\n" +
            "    \"git_url\": \"git://github.com/marvas/DAT210.git\",\n" +
            "    \"ssh_url\": \"git@github.com:marvas/DAT210.git\",\n" +
            "    \"clone_url\": \"https://github.com/marvas/DAT210.git\",\n" +
            "    \"svn_url\": \"https://github.com/marvas/DAT210\",\n" +
            "    \"homepage\": null,\n" +
            "    \"size\": 104,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": null,\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  },\n" +
            "  {\n" +
            "    \"id\": 95813813,\n" +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnk5NTgxMzgxMw==\",\n" +
            "    \"name\": \"LightControl\",\n" +
            "    \"full_name\": \"marvas/LightControl\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"marvas\",\n" +
            "      \"id\": 5663505,\n" +
            "      \"node_id\": \"MDQ6VXNlcjU2NjM1MDU=\",\n" +
            "      \"avatar_url\": \"https://avatars0.githubusercontent.com/u/5663505?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/marvas\",\n" +
            "      \"html_url\": \"https://github.com/marvas\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/marvas/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/marvas/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/marvas/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/marvas/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/marvas/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/marvas/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/marvas/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/marvas/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/marvas/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/marvas/LightControl\",\n" +
            "    \"description\": null,\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/marvas/LightControl\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/marvas/LightControl/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/marvas/LightControl/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/marvas/LightControl/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/marvas/LightControl/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/marvas/LightControl/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/marvas/LightControl/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/marvas/LightControl/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/marvas/LightControl/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/marvas/LightControl/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/marvas/LightControl/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/marvas/LightControl/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/marvas/LightControl/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/marvas/LightControl/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/marvas/LightControl/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/marvas/LightControl/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/marvas/LightControl/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/marvas/LightControl/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/marvas/LightControl/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/marvas/LightControl/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/marvas/LightControl/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/marvas/LightControl/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/marvas/LightControl/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/marvas/LightControl/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/marvas/LightControl/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/marvas/LightControl/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/marvas/LightControl/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/marvas/LightControl/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/marvas/LightControl/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/marvas/LightControl/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/marvas/LightControl/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/marvas/LightControl/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/marvas/LightControl/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/marvas/LightControl/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/marvas/LightControl/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/marvas/LightControl/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/marvas/LightControl/deployments\",\n" +
            "    \"created_at\": \"2017-06-29T19:47:42Z\",\n" +
            "    \"updated_at\": \"2018-04-15T15:09:11Z\",\n" +
            "    \"pushed_at\": \"2017-08-02T17:00:01Z\",\n" +
            "    \"git_url\": \"git://github.com/marvas/LightControl.git\",\n" +
            "    \"ssh_url\": \"git@github.com:marvas/LightControl.git\",\n" +
            "    \"clone_url\": \"https://github.com/marvas/LightControl.git\",\n" +
            "    \"svn_url\": \"https://github.com/marvas/LightControl\",\n" +
            "    \"homepage\": null,\n" +
            "    \"size\": 2649,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": \"C#\",\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  },\n" +
            "  {\n" +
            "    \"id\": 50907029,\n" +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnk1MDkwNzAyOQ==\",\n" +
            "    \"name\": \"Master\",\n" +
            "    \"full_name\": \"marvas/Master\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"marvas\",\n" +
            "      \"id\": 5663505,\n" +
            "      \"node_id\": \"MDQ6VXNlcjU2NjM1MDU=\",\n" +
            "      \"avatar_url\": \"https://avatars0.githubusercontent.com/u/5663505?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/marvas\",\n" +
            "      \"html_url\": \"https://github.com/marvas\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/marvas/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/marvas/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/marvas/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/marvas/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/marvas/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/marvas/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/marvas/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/marvas/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/marvas/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/marvas/Master\",\n" +
            "    \"description\": null,\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/marvas/Master\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/marvas/Master/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/marvas/Master/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/marvas/Master/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/marvas/Master/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/marvas/Master/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/marvas/Master/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/marvas/Master/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/marvas/Master/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/marvas/Master/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/marvas/Master/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/marvas/Master/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/marvas/Master/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/marvas/Master/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/marvas/Master/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/marvas/Master/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/marvas/Master/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/marvas/Master/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/marvas/Master/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/marvas/Master/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/marvas/Master/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/marvas/Master/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/marvas/Master/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/marvas/Master/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/marvas/Master/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/marvas/Master/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/marvas/Master/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/marvas/Master/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/marvas/Master/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/marvas/Master/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/marvas/Master/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/marvas/Master/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/marvas/Master/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/marvas/Master/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/marvas/Master/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/marvas/Master/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/marvas/Master/deployments\",\n" +
            "    \"created_at\": \"2016-02-02T08:50:20Z\",\n" +
            "    \"updated_at\": \"2018-04-15T15:11:00Z\",\n" +
            "    \"pushed_at\": \"2016-06-10T12:45:40Z\",\n" +
            "    \"git_url\": \"git://github.com/marvas/Master.git\",\n" +
            "    \"ssh_url\": \"git@github.com:marvas/Master.git\",\n" +
            "    \"clone_url\": \"https://github.com/marvas/Master.git\",\n" +
            "    \"svn_url\": \"https://github.com/marvas/Master\",\n" +
            "    \"homepage\": null,\n" +
            "    \"size\": 348,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": \"Python\",\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  },\n" +
            "  {\n" +
            "    \"id\": 15761537,\n" +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxNTc2MTUzNw==\",\n" +
            "    \"name\": \"uis-map-test\",\n" +
            "    \"full_name\": \"marvas/uis-map-test\",\n" +
            "    \"owner\": {\n" +
            "      \"login\": \"marvas\",\n" +
            "      \"id\": 5663505,\n" +
            "      \"node_id\": \"MDQ6VXNlcjU2NjM1MDU=\",\n" +
            "      \"avatar_url\": \"https://avatars0.githubusercontent.com/u/5663505?v=4\",\n" +
            "      \"gravatar_id\": \"\",\n" +
            "      \"url\": \"https://api.github.com/users/marvas\",\n" +
            "      \"html_url\": \"https://github.com/marvas\",\n" +
            "      \"followers_url\": \"https://api.github.com/users/marvas/followers\",\n" +
            "      \"following_url\": \"https://api.github.com/users/marvas/following{/other_user}\",\n" +
            "      \"gists_url\": \"https://api.github.com/users/marvas/gists{/gist_id}\",\n" +
            "      \"starred_url\": \"https://api.github.com/users/marvas/starred{/owner}{/repo}\",\n" +
            "      \"subscriptions_url\": \"https://api.github.com/users/marvas/subscriptions\",\n" +
            "      \"organizations_url\": \"https://api.github.com/users/marvas/orgs\",\n" +
            "      \"repos_url\": \"https://api.github.com/users/marvas/repos\",\n" +
            "      \"events_url\": \"https://api.github.com/users/marvas/events{/privacy}\",\n" +
            "      \"received_events_url\": \"https://api.github.com/users/marvas/received_events\",\n" +
            "      \"type\": \"User\",\n" +
            "      \"site_admin\": false\n" +
            "    },\n" +
            "    \"private\": false,\n" +
            "    \"html_url\": \"https://github.com/marvas/uis-map-test\",\n" +
            "    \"description\": \"Bachelor\",\n" +
            "    \"fork\": false,\n" +
            "    \"url\": \"https://api.github.com/repos/marvas/uis-map-test\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/marvas/uis-map-test/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/marvas/uis-map-test/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/marvas/uis-map-test/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/marvas/uis-map-test/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/marvas/uis-map-test/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/marvas/uis-map-test/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/marvas/uis-map-test/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/marvas/uis-map-test/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/marvas/uis-map-test/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/marvas/uis-map-test/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/marvas/uis-map-test/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/marvas/uis-map-test/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/marvas/uis-map-test/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/marvas/uis-map-test/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/marvas/uis-map-test/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/marvas/uis-map-test/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/marvas/uis-map-test/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/marvas/uis-map-test/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/marvas/uis-map-test/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/marvas/uis-map-test/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/marvas/uis-map-test/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/marvas/uis-map-test/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/marvas/uis-map-test/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/marvas/uis-map-test/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/marvas/uis-map-test/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/marvas/uis-map-test/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/marvas/uis-map-test/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/marvas/uis-map-test/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/marvas/uis-map-test/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/marvas/uis-map-test/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/marvas/uis-map-test/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/marvas/uis-map-test/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/marvas/uis-map-test/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/marvas/uis-map-test/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/marvas/uis-map-test/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/marvas/uis-map-test/deployments\",\n" +
            "    \"created_at\": \"2014-01-09T08:55:07Z\",\n" +
            "    \"updated_at\": \"2014-06-24T23:47:18Z\",\n" +
            "    \"pushed_at\": \"2014-01-09T08:55:07Z\",\n" +
            "    \"git_url\": \"git://github.com/marvas/uis-map-test.git\",\n" +
            "    \"ssh_url\": \"git@github.com:marvas/uis-map-test.git\",\n" +
            "    \"clone_url\": \"https://github.com/marvas/uis-map-test.git\",\n" +
            "    \"svn_url\": \"https://github.com/marvas/uis-map-test\",\n" +
            "    \"homepage\": \"\",\n" +
            "    \"size\": 0,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": null,\n" +
            "    \"has_issues\": true,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "  }\n" +
            "]";
}
